[dev]
  command = "yarn run vite:start"
  publish = "dist"
  port = 5555

[build]
  command = "yarn run vite:build"
  publish = "dist"

[functions]
  node_bundler = "esbuild"
  included_files = ["netlify/data/*.json"]
  
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
